### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by SharpShooter17** [RycerzeZahira/front#19]
https://github.com/RycerzeZahira/front/blob/771bea061a1fa7adb8f24ec4728060825b9e516a/app/src/main/java/lodzka/politechnika/qrcode/fragment/AnswerFragment.java#L65

Tak nie zadziała - musisz dać w toast zamiast System.out :)

**Comment by AMordaka** [comment]
System out był w celach testowych, docelowo zostanie zmienione na toast
